"""The authored-versus-live comparison: same population on both arms, and no overclaim in the cell.

The page exists to expose a number the corpus was quietly not showing. Two things would make it
part of the problem instead: pooling a different population from the scorecard, so that two pages
disagree about the same snapshot; and reporting "authored" where the record only supports "does not
attribute to a model", which are different claims that differ by one real row (DEC-153).
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

from trace_ai.config import PROJECT_ROOT
from trace_ai.services.evaluation.authored_versus_live import (
    Pooled,
    pool_snapshot,
    render_authored_versus_live,
)

STAMP = datetime(2026, 8, 14, tzinfo=UTC)


def _snapshot(tmp_path: Path, rows: list[dict[str, object]]) -> Path:
    path = tmp_path / "history.jsonl"
    path.write_text(
        json.dumps(
            {
                "git_ref": "abcdef1234",
                "recorded_at": "2026-08-18",
                "catalog_version": "0.1",
                "prompt_digest": "sha256:x",
                "rows": rows,
            }
        )
        + "\n",
        encoding="utf-8",
    )
    return path


def _row(**overrides: object) -> dict[str, object]:
    row = {
        "scenario": "alpha",
        "condition": "clean",
        "authoritative": True,
        "matched": 1,
        "missed": 0,
        "spurious": 0,
        "model": None,
    }
    row.update(overrides)
    return row


def test_the_snapshot_pools_only_authoritative_clean_rows(tmp_path: Path) -> None:
    """DEC-143's population, so this page and the scorecard cannot disagree about one snapshot."""
    history = _snapshot(
        tmp_path,
        [
            _row(scenario="alpha"),
            _row(scenario="beta", condition="adversarial", matched=5),
            _row(scenario="gamma", authoritative=False, matched=9),
        ],
    )
    pooled = pool_snapshot(history, "Authored")
    assert pooled is not None
    assert pooled.rows == 1, "the adversarial and non-authoritative rows are excluded"
    assert pooled.matched == 1


def test_an_empty_history_yields_no_arm(tmp_path: Path) -> None:
    """A page rendering an arm with nothing behind it would be the defect it is auditing."""
    empty = tmp_path / "history.jsonl"
    empty.write_text("", encoding="utf-8")
    assert pool_snapshot(empty, "Authored") is None


def test_the_cell_reports_attribution_and_never_claims_authorship() -> None:
    """ "Does not attribute to a model" and "was authored" differ by one real row: ForgeFlow was a
    live capture whose usage predated the attribution format. The column reports what the record
    supports and the page names the exception in prose.
    """
    arm = Pooled(
        label="Authored recordings", rows=14, matched=14, missed=3, spurious=4, attributed=0
    )
    page = render_authored_versus_live([arm], generated_at=STAMP)
    assert "0 of 14 attribute to a model" in page
    assert "every row authored" not in page
    assert "ForgeFlow" in page, "the one row whose empty attribution means something else"


def test_ratios_carry_their_denominators() -> None:
    arm = Pooled(label="Live", rows=15, matched=2, missed=13, spurious=10, attributed=14)
    page = render_authored_versus_live([arm], generated_at=STAMP)
    assert "17% (2/12)" in page, "precision over produced"
    assert "13% (2/15)" in page, "recall over reachable"


def test_an_arm_that_produced_nothing_reports_a_dash_not_a_zero() -> None:
    """DEC-150's rule, applied here: a ratio over an empty denominator is not a number."""
    arm = Pooled(label="Quiet", rows=3, matched=0, missed=0, spurious=0, attributed=0)
    page = render_authored_versus_live([arm], generated_at=STAMP)
    assert "| — | — |" in page


def test_the_committed_page_agrees_with_the_committed_scorecard() -> None:
    """The live arm must pool to the same counts the scorecard's mixed-stratum row shows.

    This is the guarantee DEC-153 bought by matching DEC-143's population, and it is worth a test
    rather than a comment: the two pages are generated by different code from the same runs, and
    nothing else would notice them drifting apart.
    """
    eval_dir = PROJECT_ROOT / "docs" / "eval"
    page = (eval_dir / "authored-versus-live.md").read_text(encoding="utf-8")
    scorecard = (eval_dir / "scorecard.html").read_text(encoding="utf-8")
    live_line = next(line for line in page.splitlines() if line.startswith("| Live captures"))
    matched, missed, spurious = (cell.strip() for cell in live_line.split("|")[4:7])
    assert f"<td>{matched}</td><td>{missed}</td><td>{spurious}</td>" in scorecard, (
        "the live arm's counts appear on the scorecard's pooled row"
    )
